-- CREATE TABLES 


CREATE TABLE IF NOT EXISTS RESPONSIBILITIES (
Responsibilities_ID INTEGER PRIMARY KEY AUTOINCREMENT,
Responsibilities_Name text not null);
CREATE TABLE IF NOT EXISTS USERS (
    USERS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERS_NAME text NOT NULL,
    TAUX_HORAIRE INTEGER NOT NULL,
    BIRTHDAY text NULL,
    MAIL text NOT NULL,
    CONTACT_NUMBER INTEGER null,
    ENTITY text NULL,
    password text not null,
    Responsibilities_Name,
        FOREIGN KEY (Responsibilities_Name)
            REFERENCES RESPONSIBILITIES (Responsibilities_Name)
                ON DELETE CASCADE
                ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS PROJECTS (
    PROJECTS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROJECTS_name text NOT NULL);
CREATE TABLE IF NOT EXISTS USERS_BY_PROJECT (
    UP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIME INTEGER NOT NULL,
    USERS_ID,
    PROJECTS_ID,
    FOREIGN KEY (USERS_ID)
            REFERENCES USERS (USERS_ID)
                ON DELETE CASCADE
                ON UPDATE NO ACTION,
    FOREIGN KEY (PROJECTS_ID)
            REFERENCES PROJECTS (PROJECTS_ID)
                ON DELETE CASCADE
                ON UPDATE NO ACTION);



